name: リリース

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pages-${{ github.repository }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Java のセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Gradle のセットアップ
        uses: gradle/actions/setup-gradle@v4

      - name: Pages の設定
        uses: actions/configure-pages@v5

      - name: ビルド
        run: |
          chmod +x ./gradlew
          ./gradlew :buildPages

      - name: Markdown を HTML に変換
        uses: actions/jekyll-build-pages@v1
        with:
          source: build/pages
          destination: build/pages_converted

      - name: 成果物のアップロード
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/pages_converted
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GitHub Pagesにデプロイ
        id: deployment
        uses: actions/deploy-pages@v4
